main: com.mcidlegame.plugin.Main
version: 1.0
name: MCIdleGame
authors: [PapstSalami, Skitskurr]

commands:
  test:
    description: Tests stuff.
    usage: /<command>
  core:
    description: Teleports you to the core room.
    usage: /<command>