main: com.mcidlegame.plugin.Main
version: 1.0
name: MCIdleGame
authors: [PapstSalami, Skitskurr]

commands:
  test:
    description: Tests stuff.
    usage: /<command>
  start:
    description: Starts monster spawning.
    usage: /<command>